paths-ignore:
  # Excludes any file in a docs directory anywhere in the repository from secret scanning
  - "docs/"
  # Excludes all js files in a dist folder at the root of the repository from secret scanning
  - "/dist/*.js"
